### ISSUE TITLE
Add to CircuitPython RTD

### ISSUE THREAD

**Issue by dastels** [adafruit/Adafruit_CircuitPython_PYOA#11]
https://readthedocs.org/projects/circuitpython-choose-your-own-adventure-library/

**Comment by dastels** [comment]
@kattni

**Comment by kattni** [comment]
@dastels This was not done correctly. the URL should read readthedocs.org/projects/Adafruit_CircuitPython_PYOA. There is no way to change the URL on an existing project, you must delete it and recreate it. When you enter the "Name" when importing it should be "Adafruit CircuitPython PYOA" (no underscores). Then add me and adabot as maintainers.

**Comment by tannewt** [comment]
Why does the project name matter? Once it is added as a subproject of circuitpython the url changes anyway.

**Comment by dastels** [comment]
I made the changes

**Comment by kattni** [comment]
There was an issue with the setup. Should be resolved and done now.
