### ISSUE TITLE
Error importing gamepadshift on Pyportal

### ISSUE THREAD

**Issue by sridevr** [adafruit/Adafruit_CircuitPython_PYOA#14]
Hi, I'm trying to use CircuitPython PYOA with PyPortal, but I get this import error...
`no module named 'gamepadshift'`.

I see that `adafruit_pyoa.py` imports `cursorcontrol_cursormanager` which imports `GamePadShift` both of which should not be needed for PyPortal because it has a touch screen.

Would undoing this commit will fix the issue? https://github.com/adafruit/Adafruit_CircuitPython_PYOA/commit/6686f5d845104284c0f7fd651da7b868eb3dedab

**Comment by dhalbert** [comment]
@brentru see #12, which conditionalized the imports and then undid it. This came up in #help-with-circuitpython Sunday 3:45pm ET.

**Comment by brentru** [comment]
Resolved in https://github.com/adafruit/Adafruit_CircuitPython_PYOA/pull/16#event-2901267118, thanks @makermelissa.
