### ISSUE TITLE
CursorManager error

### ISSUE THREAD

**Issue by matgyver** [adafruit/Adafruit_CircuitPython_PYOA#34]
I updated to the recent CircuitPython and libraries and now I am getting the following error.

SD card found
Traceback (most recent call last):
  File "code.py", line 18, in <module>
  File "adafruit_pyoa.py", line 108, in __init__
NameError: name 'CursorManager' is not defined

Code done running.

Libraries were updated using the circup tool. Below is the boot_out.txt

Adafruit CircuitPython 7.3.1 on 2022-06-22; Adafruit PyGamer with samd51j19
Board ID:pygamer

**Comment by tekktrik** [comment]
Looks like the installation files are missing `adafruit-circuitpython-cursorcontrol`, PR #37 fixes it!  In the meantime, make sure [the cursor control library](https://github.com/adafruit/Adafruit_CircuitPython_CursorControl) is on your board!
