### ISSUE TITLE
Convert `.show()` to `.root_group =` for CircuitPython 9

### ISSUE THREAD

**Issue by dhalbert** [adafruit/Adafruit_CircuitPython_PYOA#39]

**Comment by prcutler** [comment]
I'm not sure about this one as it's in a class.  In `adafruit_pyoa.py` line 95, it has:

`self._display.show(self.root_group)`

Can that be updated to `self.display.root_group = self.root_group`?

**Comment by FoamyGuy** [comment]
@prcutler yep, that one should be changed as well
