### ISSUE TITLE
missing font file and font file location

### ISSUE THREAD

**Issue by jerryneedell** [adafruit/Adafruit_CircuitPython_PYOA#6]
I tried running the demo for this and ran into 2 issues with this line
https://github.com/adafruit/Adafruit_CircuitPython_PYOA/blob/master/adafruit_pyoa.py#L75

First, I don't have this font file Arial-Bold-12-- where can I get it?
I do have Arial-12 so I temproarily used it then I found that this assumes the file is at the root level of the filesystem. Isn't the convention to put fonts in a fonts/ folder?

**Comment by jerryneedell** [comment]
#7 fixes the missing file - thanks
regarding the location of the font file, I wonder if this should be passed in as an argument so the user can decide where to keep the file -- this will be especially useful if the whole example is stored on an SD card.

Having adafruit_pyoa.py assume a location may be to restrictive.

**Comment by ladyada** [comment]
taggin @dastels

**Comment by dastels** [comment]
2 thoughts:
1) we could pass the font directory into the constructor of PYOA_Graphics
2) we could have the font directory in the game asset directory (e.g. cyoa/fonts and cave/fonts)

The later has the benefit of not requiring any code changes outside the lib code as well as packaging everything for the game together.

**Comment by ladyada** [comment]
latter plz

**Comment by kattni** [comment]
This appears to have been resolved.
